package com.loopme.model;

public enum UserPermission {
    CREATE_PUBLISHER,
    UPDATE_PUBLISHER,
    DELETE_PUBLISHER,
    CREATE_OPERATOR,
    UPDATE_OPERATOR,
    DELETE_OPERATOR,
    CREATE_APPLICATION,
    UPDATE_APPLICATION,
    DELETE_APPLIATION
}
